import 'bootstrap-icons/font/bootstrap-icons.css'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SessionProvider from '@/components/ProvidersWrapper'
import { cookies } from 'next/dist/client/components/headers'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}
export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const cookieStore = cookies()
	const theme = cookieStore.get('theme')
	return (
		<html
			lang='en'
			className={theme?.value ?? ''}>
			<Script src='https://www.googletagmanager.com/gtag/js?id=G-0B2P1YZYNS' />
			<Script id='google-analytics'>
				{`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
 
          gtag('config', 'G-0B2P1YZYNS');
        `}
			</Script>
			<body
				className={` ${inter.className} bg-slate-200 dark:bg-gray-950 text-slate-700 overflow-x-hidden dark:text-slate-300 min-h-screen`}>
				<SessionProvider>{children}</SessionProvider>
			</body>
		</html>
	)
}
